### ISSUE TITLE
Support configuring test_mode

### ISSUE THREAD

**Issue by breeswish** [japaric/criterion.rs#215]
Currently test_mode is only configured from args, so it is not possible to change it programmatically. It will be nice to add setters!

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

I'm afraid that I don't really know why this is useful - could you explain in more detail?

**Comment by breeswish** [comment]
@bheisler for example, we want to parse our own args, while preserving the functionality to run in test mode.

**Comment by bheisler** [comment]
Why do you need to parse command-line arguments in your benchmarks? I think that probably suggests that you're taking the wrong approach to benchmarking.

**Comment by breeswish** [comment]
Hmm. For example, my benchmark contains large payloads which takes hours to run but provides very specific and detail performance information. It also has small payloads which run in minutes but are not as complete as the large ones. Thus, my benchmark has a command-line argument to switch the payload kind.

**Comment by bheisler** [comment]
In that case, I think you have a couple of options. You could tag your fast benchmarks with something in the name and then run them like so:

```rust
fn my_bench(c: &mut Criterion) {
    c.bench_function("bench_fast", |b| b.iter(|| /*...*/ ));
    c.bench_function("bench_slow", |b| b.iter(|| /*...*/ ));
}
// Run with `cargo bench -- fast` or `cargo bench -- slow`
```

Or you could separate your benchmarks into different benchmark targets. In Cargo.toml:
```toml
[[bench]]
name = "fast_benchmarks"
harness = false

[[bench]]
name = "slow_benchmarks"
harness = false

# Put your code in `benches/fast_benchmarks.rs` or `benches/slow_benchmarks.rs`
# Run with `cargo bench --bench fast_benchmarks` or `cargo bench --bench slow_benchmarks`
```

Either one would allow you to separate your benchmarks into different groups with a command-line option.
